### PR TITLE
catatonit: run as pause process

### PR DESCRIPTION
**Pull request by giuseppe**
allow to run catatonit as a replacement for the Kubernetes pause
process.  In addition to the basic pause process feature of just
keeping alive the namespaces, catatonit will also reap processes
created by containers sharing the pid namespace with the infra
container.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@cyphar it is a bit controversial feature that doesn't fit with catatonit so feel free to just close this PR :-)

I think though, that it could be very useful to have an enhanced version of the Kubernetes `pause` process that can also reap processes and we would probably use it as the init process for Podman infra containers

**Comment by cyphar** [comment]
https://github.com/openSUSE/catatonit/releases/tag/v0.1.7

**Comment by vrothberg** [comment]
(Back from PTO)

Thank you, @cyphar!  I'll open a PR against Podman this week.  Each pod will use catatonit by default soon :)

**Comment by cyphar** [comment]
Yay. :smile:

**Pull request merged**
